# This is a basic workflow to help you get started with Actions

name: Trigger Rebuild

# Controls when the workflow will run
on:
  workflow_dispatch:

  schedule: # “At 9am every day”
    - cron: "0 9 * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Call the webhook
        run: curl -X GET ${{ secrets.WEB_HOOK }}
