# This is a basic workflow to help you get started with Actions

name: Run lighthouse

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   schedule:
    - cron: "*/10 * * * *"
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://anshuman.vercel.app'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
